---
title: "Patternize Code Xylocopa Wing Morph"
date: 01/14/2021
output: html_notebook
---



```{r library}
library(patternize)
library(viridis)
library(rgdal)
library(abind)
library(raster)
library(sp)
library(RNiftyReg)
library(imager)
library(dplyr)


```


```{r}
#install.packages("devtools")
#library(devtools)
#install_github("StevenVB12/patternize")
```


Make image and landmark list 
```{r}
#make list with images
morphimages <- c('XC00792', #e at the end means one of the photoshopped images
'XC01140',
'XC01661',
'XC01710',
'XC01735',
'XC02038',
'XC02069',
'XC02075',
'XC02112e',
'XC02189',
'XC02196',
'XC02208',
'XC02229e',
'XC02231',
'XC02252',
'XC02254',
'XC02255e',
'XC02265e',
'XC02287',
'XC02292',
'XC02297',
'XC02325',
'XC02328',
'XC02330',
'XC02334e',
'XC02431',
'XC02448',
'XC02458',
'XC02512',
'XC02515',
'XC02537',
'XC02540',
'XC02549e',
'XC02567',
'XC02575',
'XC03729',
'XC05506',
'XC05515',
'XC05734',
'XC07565',
'XC09050',
'XC09100e',
'XC12532',
'XC14486',
'XC14501',
'XC14627',
'XC14759',
'XC15037e',
'XC15183e',
'XC15353',
'XC15495',
'XC15496',
'XC15559',
'XC15685',
'XC15692e',
'XC15925',
'XC16134',
'XC16760',
'XC16873e',
'XC18446',
'XC20482',
'XC20483',
'XC20631')


prepath<- 'Morph.photos'
extension <- '.jpg'
imageListMorph <- makeList(morphimages, 'image', prepath, extension)

#make list with landmarks
morphlandmarks <- c('XC00792', #e at the end means one of the photoshopped images
'XC01140',
'XC01661',
'XC01710',
'XC01735',
'XC02038',
'XC02069',
'XC02075',
'XC02112e',
'XC02189',
'XC02196',
'XC02208',
'XC02229e',
'XC02231',
'XC02252',
'XC02254',
'XC02255e',
'XC02265e',
'XC02287',
'XC02292',
'XC02297',
'XC02325',
'XC02328',
'XC02330',
'XC02334e',
'XC02431',
'XC02448',
'XC02458',
'XC02512',
'XC02515',
'XC02537',
'XC02540',
'XC02549e',
'XC02567',
'XC02575',
'XC03729',
'XC05506',
'XC05515',
'XC05734',
'XC07565',
'XC09050',
'XC09100e',
'XC12532',
'XC14486',
'XC14501',
'XC14627',
'XC14759',
'XC15037e',
'XC15183e',
'XC15353',
'XC15495',
'XC15496',
'XC15559',
'XC15685',
'XC15692e',
'XC15925',
'XC16134',
'XC16760',
'XC16873e',
'XC18446',
'XC20482',
'XC20483',
'XC20631')

prepath<- 'Morph.Landmarks'
extension <- '_landmark.txt'
landmarklistMorph <- makeList(morphlandmarks, 'landmark', prepath, extension)

target <-landmarklistMorph[['XC15925']] 
mask1 <- read.table('cartoon/XC15925-outline points.txt')
outline <- read.table('cartoon/XC15925-outline points.txt')
```

```{r}
imageList_alignedMorph<- alignLan(imageListMorph, landmarklistMorph, transformRef = target, adjustCoords = TRUE,
                              plotTransformed = T, resampleFactor = 5, cartoonID = 'XC15925', 
                             maskOutline = mask1)
 
# Run K-means over all images
 
par(mfrow=c(2,1))
rasterList_Morph <- patK(imageList_alignedMorph, k=2, plot = T,
                        maskToNA = 0, kmeansOnAll = TRUE)


 
# plot the k-means results
 
summedRaster_Morph <- sumRaster(rasterList_Morph, morphimages, type = 'k')
 
colfunc <- inferno(100)
plotHeat(summedRaster_Morph, morphimages, plotCartoon = TRUE, refShape = target, outline = outline,
         landList = landmarklistMorph, adjustCoords = TRUE, flipRaster = 'y',
         imageList = imageListMorph, cartoonID = 'XC15925', cartoonFill = 'black', cartoonCol = 'gray35',
         cartoonOrder = 'under', colpalette = colfunc)


#save(rasterList_Morph, file = 'output/morphoutput.rda')

load('output/morphoutput.rda')

```

#Non morph control 
```{r}
nonmorphimages <- c('XC00134', 'XC00173', 'XC00182' , 'XC00792', 'XC01620', 'XC01644', 'XC01747', 'XC02055', 'XC02183', 'XC02719')

prepath<- 'Nonmorph.photos'
extension <- '.jpg'
imageListNM <- makeList(nonmorphimages, 'image', prepath, extension)

nonmorphlandmark <- c('XC00134', 'XC00173', 'XC00182' , 'XC00792', 'XC01620', 'XC01644', 'XC01747', 'XC02055', 'XC02183', 'XC02719')

prepath<- 'Nonmorph.Landmarks'
extension <- '_landmark.txt'
landmarklistNM <- makeList(nonmorphlandmark, 'landmark', prepath, extension)

#target <-landmarklistNM[['XC00792']] 
#mask1 <- read.table('cartoon/XC00792-outline points.txt')
#outline <- read.table('cartoon/XC00792-outline points.txt')
```


```{r}
imageList_alignedNM<- alignLan(imageListNM, landmarklistNM, transformRef = target, adjustCoords = TRUE,
                              plotTransformed = T, resampleFactor = 5, cartoonID = 'XC00792', 
                             maskOutline = mask1)
 

# Run K-means over all images
 

par(mfrow=c(2,1))
rasterList_NM <- patK(imageList_alignedNM, k=2, plot = T,
                        maskToNA = 0, kmeansOnAll = TRUE)

#save(rasterList_NM, file = 'output/nonmorphoutput.rda')

load('output/nonmorphoutput.rda')

 
# plot the k-means results
 
summedRaster_NM <- sumRaster(rasterList_NM, nonmorphimages, type = 'k')
 
colfunc <- inferno(100)
plotHeat(summedRaster_NM, nonmorphimages, plotCartoon = TRUE, refShape = target, outline = outline,
         landList = landmarkList, adjustCoords = TRUE, flipRaster = 'y',
         imageList = imageListNM, cartoonID = 'XC00792', cartoonFill = 'black', cartoonCol = 'gray35',
         cartoonOrder = 'under', colpalette = colfunc)

```


subtract rasters -- difference appears same as morph indicating that there is little difference among non-morph wings
```{r}

subtracted <- summedRaster_NM[[2]] - summedRaster_Morph[[1]]

colfunc <- c("blue","lightblue","black","pink","red")
plotHeat(subtracted, imageListMorph, plotCartoon = TRUE, refShape = 'target', outline = outline, 
         crop = c(200,2800,300,1800),landList = landmarklistMoprh, adjustCoords = TRUE, imageList = imageListMorph, 
         flipRaster = 'y', flipOutline = 'y', cartoonID = 'XC15925', zlim=c(-1,1), colpalette= colfunc, 
         cartoonFill = 'black', cartoonOrder = 'under', legendTitle = 'Difference')


```






